config/routes.rb
Rails.application.routes.draw do

  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users 
         
 resources :profiles      
    

 get 'profiles/subregion_options' => 'profiles#subregion_options'
  get 'surveys/subregion_options' => 'surveys#subregion_options'
  get 'surveys/review' => "surveys#review"
  	resources :surveys do
       member do
        get :finish
        put :finish
        get :approve
        put :approve
        post :approve        
        get :new_profile
        get :edit_profile

      post :create_profile      
      get :new_response
      post :create_response
    end
        end
  root 'surveys#index'








  end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :profilable, polymorphic: true, optional: true
  enum gender: ["Female", "Male"]
  enum lang: ["English", "Deutsche", "Francais", "Español", "Chinese", "Korean", "Turkish"]
#attr_accessor :country_code, :state_code
validates :country_code, :state_code, :birthday, presence: true, if: :profilable_type?



def profilable_type?
self.profilable_type == "User"
	
end





end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :profile]
  before_action :check_user_profile, except: [:new, :create, :subregion_options]

  # GET /profiles
  # GET /profiles.json
  def index    
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @country = Carmen::Country.coded(@profile.country_code)
    @subregions = @country.subregions
    @state = @subregions.coded(@profile.state_code)
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end



  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(pro_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { redirect_to new_profile_path, alert: 'Please fill all fields'  }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(pro_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def subregion_options
  render partial: 'subregion_select'
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.fetch(:profile, {})
    end

    def pro_params

      params.require(:profile).permit(:country_code, :state_code, :gender, :lang, :birthday)
      
    end

    def check_user_profile

      if current_user.profile.nil?
        flash[:alert] = "You have to create profile before any activity"
      redirect_to new_profile_path
    elsif @profile.profilable_id != current_user.id
      flash[:alert] = "You don't have permission to show this page"
      redirect_to root_path
      end      
      
    end




end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.slim
doctype html
html
  head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
      = form_for (@profile), :html => { :multipart => true , :class => 'form-horizontal' } do |f|  
        = f.fields_for :profile do |ff|    
          = f.hidden_field :profilable_id
          div id="profile"
           = f.label "Country"
        br
        = f.country_select :country_code, priority: %w(US CA), prompt: 'Please select a country'
        br
        #field
          = f.label "City"
          br
          = render 'subregion_select', locals: {parent_region: f.object.country_code}
        br
        = f.label "Gender"
        br
        = f.select :gender, Profile.genders.keys.to_a
        br
        = f.label "Your Language"
        br
        = f.select :lang, Profile.langs.keys.to_a
        br
        = f.label "Birthdate"
        br
        = f.date_field :birthday

        
        

        = f.submit 'Send', class: "btn btn-primary"

app/views/profiles/_subregion_select.html.slim
#profile_state_code_wrapper
  - parent_region ||= params[:parent_region]
  - country = Carmen::Country.coded(parent_region)

  - if country.nil? 
    em Please select a country above
  - elsif country.subregions? 
    = subregion_select(:profile, :state_code, parent_region) 
  - else 
    = text_field(:profile, :state_code) 
  

app/views/profiles/edit.html.slim
h1 Editing profile

== render 'form'

=> link_to 'Show', @profile
'|
=< link_to 'Back', profiles_path

app/views/profiles/index.html.slim
h1 Listing profiles

table
  thead
    tr
      th
      th
      th

  tbody
    - @profiles.each do |profile|
      tr
        td = link_to 'Show', profile
        td = link_to 'Edit', edit_profile_path(profile)
        td = link_to 'Destroy', profile, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.slim
h1 New profile

== render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.slim
#div class="container"
 ol
  	h3 = "Your:( #{@profile.profilable_id}. id's) Profile"
 	li	
 		= "User Role:  #{current_user.role}"
 	li	
 		= "Country:  #{@country.name}"
	li	
		= "State:  #{@state.name}"
	li	
		= "Gender:  #{@profile.gender}"
	li	
		= "Preferred Language: #{@profile.lang}"
	li	
		= "Age: #{Time.now.utc.to_date.year - @profile.birthday.year}"


=> link_to 'Edit', edit_profile_path(@profile)
'|
=< link_to 'Home', root_path